server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitlab.com/ms-2020-04/ms-boot-cloud.git
          searchPaths: config-data
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}
  security:
    user:
      name: root
      password: s3cr3t
